/**
 * Aggregates the member's pending external transfers — both directions —
 * for the Thanh toán tab. Money handling lives outside the system; this
 * just surfaces what each side still needs to do.
 *
 * Buckets:
 *   - outgoing pass_slot: claimer waiting to confirm payment to the original
 *     voter (auto-match seat reassignment leaves `claimedAt` set,
 *     `confirmedAt` null until the user clicks "Đã thanh toán").
 *   - outgoing vang_lai_quy: member with a `vang_lai` vote on a `done` month
 *     who hasn't self-marked the quỹ transfer.
 *   - incoming pass_slot: original voter whose slot got claimed but the
 *     claimer hasn't confirmed payment yet. Read-only — they wait on the
 *     claimer's button.
 *
 * Monthly registration ("đóng tiền tháng") is handled outside the system —
 * the app only tracks payments generated by vãng lai registration + pass slot.
 */
import { and, asc, eq, inArray, isNotNull, isNull } from "drizzle-orm";
import { getDb, schema } from "~/db/client";
import { CONFIG_KEYS, getPrices, getString, type PriceTable } from "./config.server";
import type { WeekdayCode } from "./dates";
import { enrichPassRequests } from "./pass-request-enrich.server";
import { priceForPassClaim, priceForVangLaiQuy } from "./pricing";

export type PaymentDirection = "out" | "in";
export type PaymentKind = "pass_slot" | "vang_lai_quy" | "pass_refund";

export interface PendingPaymentItem {
  id: string;
  direction: PaymentDirection;
  kind: PaymentKind;
  amount: number;
  sessionDate: string;
  sessionWeekday: WeekdayCode;
  counterpartyName: string;
  counterpartyPhone: string | null;
  counterpartyQrUrl: string | null;
  counterpartyMomoLink: string | null;
  /** Action present only on outgoing items the user owes and can mark paid. */
  confirm?: {
    intent: "confirm-pass-payment" | "mark-vang-lai-paid" | "fund-mark-refund-paid";
    targetId: string;
  };
  /** Set on done items (from loadDonePayments). Unix ms of when payment was
   * confirmed/marked-paid. */
  paidAt?: number;
}

export interface PendingPaymentsSummary {
  outgoing: PendingPaymentItem[];
  incoming: PendingPaymentItem[];
}

const QUY_NAME = "Quỹ chung";

export async function loadPendingPayments(
  d1: D1Database,
  userId: string,
): Promise<PendingPaymentsSummary> {
  const db = getDb(d1);
  const [prices, adminQrKey, quyMomoLink, me] = await Promise.all([
    getPrices(d1),
    getString(d1, CONFIG_KEYS.ADMIN_QR_IMAGE_KEY, ""),
    getString(d1, CONFIG_KEYS.QUY_MOMO_LINK, ""),
    db.query.users.findFirst({ where: eq(schema.users.id, userId) }),
  ]);
  if (!me) return { outgoing: [], incoming: [] };
  const adminQrUrl = adminQrKey ? `/qr/${encodeURIComponent(adminQrKey)}` : null;
  const quyMomo = quyMomoLink || null;

  const [outgoingPass, outgoingVangLai, incomingPass, incomingRefunds] = await Promise.all([
    loadOutgoingPassSlots(d1, userId, prices),
    loadOutgoingVangLaiQuy(d1, me, prices, adminQrUrl, quyMomo),
    loadIncomingPassSlots(d1, userId, prices),
    loadIncomingRefunds(d1, userId, { paid: false }),
  ]);

  return {
    outgoing: [...outgoingPass, ...outgoingVangLai].sort(byDateAsc),
    incoming: [...incomingPass, ...incomingRefunds].sort(byDateAsc),
  };
}

function byDateAsc(a: PendingPaymentItem, b: PendingPaymentItem) {
  return a.sessionDate.localeCompare(b.sessionDate);
}

async function loadOutgoingPassSlots(
  d1: D1Database,
  userId: string,
  prices: PriceTable,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  const rows = await db.query.passRequests.findMany({
    where: and(
      eq(schema.passRequests.claimedByUserId, userId),
      isNull(schema.passRequests.confirmedAt),
    ),
    orderBy: [asc(schema.passRequests.claimedAt)],
  });
  const enriched = await enrichPassRequests(d1, rows);
  return enriched.map(({ request, owner, session }) => ({
    id: `passout-${request.id}`,
    direction: "out",
    kind: "pass_slot",
    amount: priceForPassClaim(request, owner.gender, prices),
    sessionDate: session.date,
    sessionWeekday: session.weekday as WeekdayCode,
    counterpartyName: owner.name,
    counterpartyPhone: owner.phone,
    counterpartyQrUrl: owner.qrImageKey
      ? `/qr/${encodeURIComponent(owner.qrImageKey)}`
      : null,
    counterpartyMomoLink: owner.momoLink ?? null,
    confirm: { intent: "confirm-pass-payment", targetId: request.id },
  }));
}

async function loadOutgoingVangLaiQuy(
  d1: D1Database,
  me: schema.User,
  prices: PriceTable,
  adminQrUrl: string | null,
  quyMomoLink: string | null,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  // Auto-matched vãng lai (got passed a slot) becomes status='thang', so
  // filtering on status='vang_lai' alone naturally excludes them. We also
  // require originalVoterId IS NULL in case future flows ever leave the
  // status as vang_lai after a chain.
  const candidates = await db.query.votes.findMany({
    where: and(
      eq(schema.votes.userId, me.id),
      eq(schema.votes.status, "vang_lai"),
      isNull(schema.votes.originalVoterId),
    ),
  });
  if (candidates.length === 0) return [];

  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      candidates.map((v) => v.playSessionId),
    ),
  });
  const sessionById = new Map(sessions.map((s) => [s.id, s] as const));

  const months = await db.query.months.findMany({
    where: inArray(
      schema.months.id,
      Array.from(new Set(sessions.map((s) => s.monthId))),
    ),
  });
  const doneMonthIds = new Set(months.filter((m) => m.status === "done").map((m) => m.id));

  const eligible = candidates.filter((v) => {
    const s = sessionById.get(v.playSessionId);
    return s && doneMonthIds.has(s.monthId);
  });
  if (eligible.length === 0) return [];

  // We already have `candidates` (my vang_lai votes) — query paid rows
  // directly to avoid re-running the votes query inside the public helper.
  const paid = await db.query.vangLaiPayments.findMany({
    where: inArray(
      schema.vangLaiPayments.voteId,
      eligible.map((v) => v.id),
    ),
  });
  const paidSet = new Set(paid.map((p) => p.voteId));
  const amount = priceForVangLaiQuy(me.gender, prices);

  return eligible
    .filter((v) => !paidSet.has(v.id))
    .map((v) => {
      const s = sessionById.get(v.playSessionId)!;
      return {
        id: `vlquy-${v.id}`,
        direction: "out" as const,
        kind: "vang_lai_quy" as const,
        amount,
        sessionDate: s.date,
        sessionWeekday: s.weekday as WeekdayCode,
        counterpartyName: QUY_NAME,
        counterpartyPhone: null,
        counterpartyQrUrl: adminQrUrl,
        counterpartyMomoLink: quyMomoLink,
        confirm: { intent: "mark-vang-lai-paid", targetId: v.id },
      };
    });
}

async function loadIncomingPassSlots(
  d1: D1Database,
  userId: string,
  prices: PriceTable,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  // Pass requests across the whole system in the "claimed but not yet
  // confirmed" window. This list is bounded (only auto-match leaves it
  // populated, only between match and confirm/cutoff) so it's cheaper than
  // fetching all of my votes first.
  const awaiting = await db.query.passRequests.findMany({
    where: and(
      isNotNull(schema.passRequests.claimedAt),
      isNull(schema.passRequests.confirmedAt),
    ),
  });
  if (awaiting.length === 0) return [];

  const myVotes = await db.query.votes.findMany({
    where: and(
      eq(schema.votes.userId, userId),
      inArray(
        schema.votes.id,
        awaiting.map((r) => r.voteId),
      ),
    ),
  });
  if (myVotes.length === 0) return [];

  const voteById = new Map(myVotes.map((v) => [v.id, v] as const));
  const me = await db.query.users.findFirst({ where: eq(schema.users.id, userId) });
  if (!me) return [];

  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      Array.from(new Set(myVotes.map((v) => v.playSessionId))),
    ),
  });
  const sessionById = new Map(sessions.map((s) => [s.id, s] as const));

  const claimerIds = Array.from(
    new Set(
      awaiting
        .filter((r) => voteById.has(r.voteId) && r.claimedByUserId)
        .map((r) => r.claimedByUserId!),
    ),
  );
  const claimers = claimerIds.length
    ? await db.query.users.findMany({ where: inArray(schema.users.id, claimerIds) })
    : [];
  const claimerById = new Map(claimers.map((u) => [u.id, u] as const));

  const out: PendingPaymentItem[] = [];
  for (const r of awaiting) {
    const vote = voteById.get(r.voteId);
    if (!vote || !r.claimedByUserId) continue;
    const session = sessionById.get(vote.playSessionId);
    if (!session) continue;
    const claimer = claimerById.get(r.claimedByUserId);
    if (!claimer) continue;
    out.push({
      id: `passin-${r.id}`,
      direction: "in",
      kind: "pass_slot",
      amount: priceForPassClaim(r, me.gender, prices),
      sessionDate: session.date,
      sessionWeekday: session.weekday as WeekdayCode,
      counterpartyName: claimer.name,
      counterpartyPhone: claimer.phone,
      counterpartyQrUrl: claimer.qrImageKey
        ? `/qr/${encodeURIComponent(claimer.qrImageKey)}`
        : null,
      counterpartyMomoLink: claimer.momoLink ?? null,
    });
  }
  return out;
}

/**
 * Mirror of `loadPendingPayments` but for items that have already been
 * confirmed/marked-paid. Powers the "Đã xong" tab in /thanh-toan.
 *
 * Sort order is paidAt-desc (most recent payment first) so the tab reads as
 * a transaction history. No pagination yet — the membership is small and
 * volume per month is bounded.
 */
export async function loadDonePayments(
  d1: D1Database,
  userId: string,
): Promise<PendingPaymentsSummary> {
  const db = getDb(d1);
  const [prices, adminQrKey, quyMomoLink, me] = await Promise.all([
    getPrices(d1),
    getString(d1, CONFIG_KEYS.ADMIN_QR_IMAGE_KEY, ""),
    getString(d1, CONFIG_KEYS.QUY_MOMO_LINK, ""),
    db.query.users.findFirst({ where: eq(schema.users.id, userId) }),
  ]);
  if (!me) return { outgoing: [], incoming: [] };
  const adminQrUrl = adminQrKey ? `/qr/${encodeURIComponent(adminQrKey)}` : null;
  const quyMomo = quyMomoLink || null;

  const [doneOutPass, doneOutVL, doneInPass, doneInRefunds] = await Promise.all([
    loadDoneOutgoingPassSlots(d1, userId, prices),
    loadDoneOutgoingVangLaiQuy(d1, me, prices, adminQrUrl, quyMomo),
    loadDoneIncomingPassSlots(d1, userId, prices),
    loadIncomingRefunds(d1, userId, { paid: true }),
  ]);

  return {
    outgoing: [...doneOutPass, ...doneOutVL].sort(byPaidAtDesc),
    incoming: [...doneInPass, ...doneInRefunds].sort(byPaidAtDesc),
  };
}

function byPaidAtDesc(a: PendingPaymentItem, b: PendingPaymentItem) {
  return (b.paidAt ?? 0) - (a.paidAt ?? 0);
}

/**
 * Refunds from quỹ to a specific member — used by both pending ("Cần thu")
 * and done ("Đã thu") views via the `paid` flag.
 */
async function loadIncomingRefunds(
  d1: D1Database,
  userId: string,
  opts: { paid: boolean },
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  // Bound the refund scan by my hoan_tien votes first.
  const myVotes = await db.query.votes.findMany({
    where: and(eq(schema.votes.userId, userId), eq(schema.votes.status, "hoan_tien")),
  });
  if (myVotes.length === 0) return [];
  const refunds = await db.query.refundPayments.findMany({
    where: and(
      inArray(
        schema.refundPayments.voteId,
        myVotes.map((v) => v.id),
      ),
      opts.paid
        ? isNotNull(schema.refundPayments.paidAt)
        : isNull(schema.refundPayments.paidAt),
    ),
  });
  if (refunds.length === 0) return [];
  const voteById = new Map(myVotes.map((v) => [v.id, v] as const));
  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      Array.from(new Set(myVotes.map((v) => v.playSessionId))),
    ),
  });
  const sessionById = new Map(sessions.map((s) => [s.id, s] as const));

  const out: PendingPaymentItem[] = [];
  for (const r of refunds) {
    const v = voteById.get(r.voteId);
    if (!v) continue;
    const s = sessionById.get(v.playSessionId);
    if (!s) continue;
    out.push({
      id: `refund-${opts.paid ? "done" : "pending"}-${r.voteId}`,
      direction: "in",
      kind: "pass_refund",
      amount: r.amount,
      sessionDate: s.date,
      sessionWeekday: s.weekday as WeekdayCode,
      counterpartyName: QUY_NAME,
      counterpartyPhone: null,
      counterpartyQrUrl: null,
      counterpartyMomoLink: null,
      paidAt: opts.paid ? r.paidAt ?? undefined : undefined,
    });
  }
  return out;
}

async function loadDoneOutgoingPassSlots(
  d1: D1Database,
  userId: string,
  prices: PriceTable,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  const rows = await db.query.passRequests.findMany({
    where: and(
      eq(schema.passRequests.claimedByUserId, userId),
      isNotNull(schema.passRequests.confirmedAt),
    ),
  });
  const enriched = await enrichPassRequests(d1, rows);
  return enriched.map(({ request, owner, session }) => ({
    id: `passout-done-${request.id}`,
    direction: "out",
    kind: "pass_slot",
    amount: priceForPassClaim(request, owner.gender, prices),
    sessionDate: session.date,
    sessionWeekday: session.weekday as WeekdayCode,
    counterpartyName: owner.name,
    counterpartyPhone: owner.phone,
    counterpartyQrUrl: owner.qrImageKey
      ? `/qr/${encodeURIComponent(owner.qrImageKey)}`
      : null,
    counterpartyMomoLink: owner.momoLink ?? null,
    paidAt: request.confirmedAt ?? undefined,
  }));
}

async function loadDoneOutgoingVangLaiQuy(
  d1: D1Database,
  me: schema.User,
  prices: PriceTable,
  adminQrUrl: string | null,
  quyMomoLink: string | null,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  const myVotes = await db.query.votes.findMany({
    where: and(
      eq(schema.votes.userId, me.id),
      eq(schema.votes.status, "vang_lai"),
      isNull(schema.votes.originalVoterId),
    ),
  });
  if (myVotes.length === 0) return [];
  const paid = await db.query.vangLaiPayments.findMany({
    where: inArray(
      schema.vangLaiPayments.voteId,
      myVotes.map((v) => v.id),
    ),
  });
  if (paid.length === 0) return [];
  const paidById = new Map(paid.map((p) => [p.voteId, p] as const));
  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      Array.from(new Set(myVotes.map((v) => v.playSessionId))),
    ),
  });
  const sessionById = new Map(sessions.map((s) => [s.id, s] as const));
  const amount = priceForVangLaiQuy(me.gender, prices);

  const out: PendingPaymentItem[] = [];
  for (const v of myVotes) {
    const p = paidById.get(v.id);
    if (!p) continue;
    const s = sessionById.get(v.playSessionId);
    if (!s) continue;
    out.push({
      id: `vlquy-done-${v.id}`,
      direction: "out",
      kind: "vang_lai_quy",
      amount,
      sessionDate: s.date,
      sessionWeekday: s.weekday as WeekdayCode,
      counterpartyName: QUY_NAME,
      counterpartyPhone: null,
      counterpartyQrUrl: adminQrUrl,
      counterpartyMomoLink: quyMomoLink,
      paidAt: p.paidAt,
    });
  }
  return out;
}

async function loadDoneIncomingPassSlots(
  d1: D1Database,
  userId: string,
  prices: PriceTable,
): Promise<PendingPaymentItem[]> {
  const db = getDb(d1);
  // Start from my votes to bound the pass-request scan.
  const myVotes = await db.query.votes.findMany({
    where: eq(schema.votes.userId, userId),
  });
  if (myVotes.length === 0) return [];
  const confirmed = await db.query.passRequests.findMany({
    where: and(
      inArray(
        schema.passRequests.voteId,
        myVotes.map((v) => v.id),
      ),
      isNotNull(schema.passRequests.confirmedAt),
    ),
  });
  if (confirmed.length === 0) return [];

  const me = await db.query.users.findFirst({ where: eq(schema.users.id, userId) });
  if (!me) return [];

  const voteById = new Map(myVotes.map((v) => [v.id, v] as const));
  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      Array.from(new Set(myVotes.map((v) => v.playSessionId))),
    ),
  });
  const sessionById = new Map(sessions.map((s) => [s.id, s] as const));

  const claimerIds = Array.from(
    new Set(
      confirmed
        .filter((r) => voteById.has(r.voteId) && r.claimedByUserId)
        .map((r) => r.claimedByUserId!),
    ),
  );
  const claimers = claimerIds.length
    ? await db.query.users.findMany({ where: inArray(schema.users.id, claimerIds) })
    : [];
  const claimerById = new Map(claimers.map((u) => [u.id, u] as const));

  const out: PendingPaymentItem[] = [];
  for (const r of confirmed) {
    const vote = voteById.get(r.voteId);
    if (!vote || !r.claimedByUserId) continue;
    const session = sessionById.get(vote.playSessionId);
    if (!session) continue;
    const claimer = claimerById.get(r.claimedByUserId);
    if (!claimer) continue;
    out.push({
      id: `passin-done-${r.id}`,
      direction: "in",
      kind: "pass_slot",
      amount: priceForPassClaim(r, me.gender, prices),
      sessionDate: session.date,
      sessionWeekday: session.weekday as WeekdayCode,
      counterpartyName: claimer.name,
      counterpartyPhone: claimer.phone,
      counterpartyQrUrl: claimer.qrImageKey
        ? `/qr/${encodeURIComponent(claimer.qrImageKey)}`
        : null,
      counterpartyMomoLink: claimer.momoLink ?? null,
      paidAt: r.confirmedAt ?? undefined,
    });
  }
  return out;
}

/**
 * Fund-wide view powering /admin/payments. Same `PendingPaymentItem` shape so
 * the UI reuses the /thanh-toan card style.
 *
 * `outgoing` = refunds the fund still owes members (pass-slot hoan_tien rows
 * not yet marked paid). `incoming` = vãng-lai → quỹ amounts the fund still
 * needs to collect from members (vang_lai votes without a self-marked payment).
 *
 * `paid` flag toggles between pending and done views.
 */
export async function loadFundPayments(
  d1: D1Database,
  opts: { paid: boolean },
): Promise<PendingPaymentsSummary> {
  const db = getDb(d1);
  const prices = await getPrices(d1);

  // ---- Outgoing (refunds) ----
  const refunds = await db.query.refundPayments.findMany({
    where: opts.paid
      ? isNotNull(schema.refundPayments.paidAt)
      : isNull(schema.refundPayments.paidAt),
  });
  const outgoing: PendingPaymentItem[] = [];
  if (refunds.length) {
    const voteIds = refunds.map((r) => r.voteId);
    const votes = await db.query.votes.findMany({
      where: inArray(schema.votes.id, voteIds),
    });
    const voteById = new Map(votes.map((v) => [v.id, v] as const));
    const memberIds = Array.from(new Set(votes.map((v) => v.userId)));
    const sessionIds = Array.from(new Set(votes.map((v) => v.playSessionId)));
    const [members, sessions] = await Promise.all([
      memberIds.length
        ? db.query.users.findMany({ where: inArray(schema.users.id, memberIds) })
        : Promise.resolve([] as schema.User[]),
      sessionIds.length
        ? db.query.playSessions.findMany({
            where: inArray(schema.playSessions.id, sessionIds),
          })
        : Promise.resolve([] as schema.PlaySession[]),
    ]);
    const memberById = new Map(members.map((u) => [u.id, u] as const));
    const sessionById = new Map(sessions.map((s) => [s.id, s] as const));
    for (const r of refunds) {
      const vote = voteById.get(r.voteId);
      if (!vote) continue;
      const member = memberById.get(vote.userId);
      const session = sessionById.get(vote.playSessionId);
      if (!member || !session) continue;
      outgoing.push({
        id: `fund-refund-${r.voteId}`,
        direction: "out",
        kind: "pass_refund",
        amount: r.amount,
        sessionDate: session.date,
        sessionWeekday: session.weekday as WeekdayCode,
        counterpartyName: member.name,
        counterpartyPhone: member.phone,
        counterpartyQrUrl: member.qrImageKey
          ? `/qr/${encodeURIComponent(member.qrImageKey)}`
          : null,
        counterpartyMomoLink: member.momoLink ?? null,
        confirm: opts.paid ? undefined : { intent: "fund-mark-refund-paid", targetId: r.voteId },
        paidAt: opts.paid ? r.paidAt ?? undefined : undefined,
      });
    }
  }

  // ---- Incoming (vãng-lai → quỹ) ----
  const vangLaiVotes = await db.query.votes.findMany({
    where: and(
      eq(schema.votes.status, "vang_lai"),
      isNull(schema.votes.originalVoterId),
    ),
  });
  const incoming: PendingPaymentItem[] = [];
  if (vangLaiVotes.length) {
    const voteIds = vangLaiVotes.map((v) => v.id);
    const sessionIds = Array.from(new Set(vangLaiVotes.map((v) => v.playSessionId)));
    const [sessions, payments] = await Promise.all([
      db.query.playSessions.findMany({
        where: inArray(schema.playSessions.id, sessionIds),
      }),
      db.query.vangLaiPayments.findMany({
        where: inArray(schema.vangLaiPayments.voteId, voteIds),
      }),
    ]);
    const sessionById = new Map(sessions.map((s) => [s.id, s] as const));
    const monthIds = Array.from(new Set(sessions.map((s) => s.monthId)));
    const months = monthIds.length
      ? await db.query.months.findMany({
          where: inArray(schema.months.id, monthIds),
        })
      : [];
    const doneMonthIds = new Set(
      months.filter((m) => m.status === "done").map((m) => m.id),
    );
    const paidById = new Map(payments.map((p) => [p.voteId, p] as const));
    const memberIds = Array.from(new Set(vangLaiVotes.map((v) => v.userId)));
    const members = memberIds.length
      ? await db.query.users.findMany({ where: inArray(schema.users.id, memberIds) })
      : [];
    const memberById = new Map(members.map((u) => [u.id, u] as const));
    for (const v of vangLaiVotes) {
      const paid = paidById.get(v.id);
      const session = sessionById.get(v.playSessionId);
      if (!session || !doneMonthIds.has(session.monthId)) continue;
      const matchesFilter = opts.paid ? !!paid : !paid;
      if (!matchesFilter) continue;
      const member = memberById.get(v.userId);
      if (!member) continue;
      incoming.push({
        id: `fund-vl-${v.id}`,
        direction: "in",
        kind: "vang_lai_quy",
        amount: priceForVangLaiQuy(member.gender, prices),
        sessionDate: session.date,
        sessionWeekday: session.weekday as WeekdayCode,
        counterpartyName: member.name,
        counterpartyPhone: member.phone,
        counterpartyQrUrl: member.qrImageKey
          ? `/qr/${encodeURIComponent(member.qrImageKey)}`
          : null,
        counterpartyMomoLink: member.momoLink ?? null,
        paidAt: opts.paid ? paid?.paidAt ?? undefined : undefined,
      });
    }
  }

  return opts.paid
    ? {
        outgoing: outgoing.sort(byPaidAtDesc),
        incoming: incoming.sort(byPaidAtDesc),
      }
    : {
        outgoing: outgoing.sort(byDateAsc),
        incoming: incoming.sort(byDateAsc),
      };
}

/** Admin marks a refund as paid. Returns false if already paid or not found. */
export async function markRefundPaid(
  d1: D1Database,
  voteId: string,
  adminUserId: string,
): Promise<{ ok: true } | { error: string; status?: number }> {
  const db = getDb(d1);
  const row = await db.query.refundPayments.findFirst({
    where: eq(schema.refundPayments.voteId, voteId),
  });
  if (!row) return { error: "Không tìm thấy khoản hoàn tiền.", status: 404 };
  if (row.paidAt) return { error: "Đã ghi nhận trước đó.", status: 400 };
  const now = Date.now();
  await db
    .update(schema.refundPayments)
    .set({ paidAt: now, paidByUserId: adminUserId })
    .where(eq(schema.refundPayments.voteId, voteId));
  return { ok: true };
}

/**
 * Voted-vãng-lai voteIds the user has self-marked as paid. Used by both the
 * Thanh toán tab (filter "Cần chuyển") AND the trang-chu banner suppressor —
 * keeping the lookup in one place keeps the two UIs consistent without each
 * route writing its own join.
 */
export async function loadMyPaidVangLaiVoteIds(
  d1: D1Database,
  userId: string,
): Promise<string[]> {
  const db = getDb(d1);
  const myVangLai = await db.query.votes.findMany({
    where: and(eq(schema.votes.userId, userId), eq(schema.votes.status, "vang_lai")),
  });
  if (myVangLai.length === 0) return [];
  const paid = await db.query.vangLaiPayments.findMany({
    where: inArray(
      schema.vangLaiPayments.voteId,
      myVangLai.map((v) => v.id),
    ),
  });
  return paid.map((p) => p.voteId);
}

/**
 * Cheap count of outstanding outgoing payments for the homepage card and
 * (eventually) the nav badge. Avoids loading the full `PendingPaymentItem`
 * payload — just two count queries.
 */
export async function loadOutstandingCount(
  d1: D1Database,
  userId: string,
): Promise<number> {
  const db = getDb(d1);

  const pendingPass = await db.query.passRequests.findMany({
    where: and(
      eq(schema.passRequests.claimedByUserId, userId),
      isNull(schema.passRequests.confirmedAt),
    ),
  });

  const myVangLai = await db.query.votes.findMany({
    where: and(
      eq(schema.votes.userId, userId),
      eq(schema.votes.status, "vang_lai"),
      isNull(schema.votes.originalVoterId),
    ),
  });
  if (myVangLai.length === 0) return pendingPass.length;

  // Only sessions in 'done' months count — pre-done vãng lai aren't ready to pay yet.
  const sessions = await db.query.playSessions.findMany({
    where: inArray(
      schema.playSessions.id,
      myVangLai.map((v) => v.playSessionId),
    ),
  });
  const months = await db.query.months.findMany({
    where: inArray(
      schema.months.id,
      Array.from(new Set(sessions.map((s) => s.monthId))),
    ),
  });
  const doneMonthIds = new Set(months.filter((m) => m.status === "done").map((m) => m.id));
  const sessionInDone = new Map(sessions.map((s) => [s.id, doneMonthIds.has(s.monthId)] as const));
  const eligibleVangLai = myVangLai.filter((v) => sessionInDone.get(v.playSessionId));
  if (eligibleVangLai.length === 0) return pendingPass.length;

  const paid = await db.query.vangLaiPayments.findMany({
    where: inArray(
      schema.vangLaiPayments.voteId,
      eligibleVangLai.map((v) => v.id),
    ),
  });
  const paidSet = new Set(paid.map((p) => p.voteId));
  const unpaidVangLai = eligibleVangLai.filter((v) => !paidSet.has(v.id)).length;

  return pendingPass.length + unpaidVangLai;
}

/** Self-marks an approved vãng lai vote as "đã chuyển quỹ" — UI-only flag. */
export async function markVangLaiPaid(
  d1: D1Database,
  userId: string,
  voteId: string,
): Promise<{ ok: true } | { error: string; status?: number }> {
  const db = getDb(d1);
  const vote = await db.query.votes.findFirst({ where: eq(schema.votes.id, voteId) });
  if (!vote) return { error: "Không tìm thấy vote.", status: 404 };
  if (vote.userId !== userId) return { error: "Không có quyền.", status: 403 };
  if (vote.status !== "vang_lai") return { error: "Vote không phải vãng lai.", status: 400 };
  const now = Date.now();
  await db
    .insert(schema.vangLaiPayments)
    .values({ voteId, userId, paidAt: now })
    .onConflictDoUpdate({
      target: schema.vangLaiPayments.voteId,
      set: { paidAt: now },
    });
  return { ok: true };
}
