import { createRequestHandler, type AppLoadContext, type ServerBuild } from "@remix-run/cloudflare";
// build/server is generated by `remix vite:build` — file may not exist before first build.
// @ts-ignore
import * as serverBuild from "./build/server";
import { handleScheduled } from "./app/lib/cron.server";

const build = serverBuild as unknown as ServerBuild;

export interface Env {
  ASSETS: Fetcher;
  DB: D1Database;
  KV: KVNamespace;
  R2: R2Bucket;
  SESSION_SECRET: string;
  APP_BASE_URL: string;
  EMAIL_FROM_ADDRESS: string;
  EMAIL_FROM_NAME: string;
  TIMEZONE: string;
  // SendGrid (set via `wrangler secret put SENDGRID_API_KEY`). See sendgrid.server.ts.
  SENDGRID_API_KEY: string;
}

const handleRemix = createRequestHandler(build, "production");

export default {
  /**
   * The `[assets]` binding handles static assets BEFORE invoking this fetch
   * handler — so anything that reaches here is a dynamic route. We hand it
   * straight to Remix.
   */
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const loadContext: AppLoadContext = {
      cloudflare: {
        env,
        ctx,
        cf: (request as Request & { cf?: IncomingRequestCfProperties }).cf,
        caches,
      },
    } as unknown as AppLoadContext;
    return handleRemix(request, loadContext);
  },

  async scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext): Promise<void> {
    ctx.waitUntil(handleScheduled(event, env));
  },
};
